### ISSUE TITLE
Sentiment datasets do not work in server environment

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/experienceAnalysis#7]
As here https://github.com/CDU-data-science-team/pxtextminingdashboard/issues/27 there is a problem deploying to RSConnect because the first time you run tidytext::get_sentiments("afinn") (or another one, I forget which offhand) you need to interact with the console to accept the licence of the data.

Users (like me) who are deploying on a server will need to download the data themselves, put it in data/, and then load it from there

**Comment by andreassot10** [comment]
@ChrisBeeley, does this f2f48dd4d56a6bcdf68872cdd18b41dacd5dfcd2 close this issue?

If yes, can you please close it?

**Comment by ChrisBeeley** [comment]
I'm assuming this must be resolved but I'm not sure 😳 

I'm going to close it and see if it comes back
